version: "3"
services:
  # namenode:
  #   image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
  #   container_name: namenode
  #   restart: always
  #   ports:
  #     - 9870:9870
  #     - 9000:9000
  #   volumes:
  #     - hadoop_namenode:/hadoop/dfs/name
  #     - ./hive-dir-init.sh:/tmp/hive-dir-init.sh
  #   environment:
  #     - CLUSTER_NAME=test
  #   env_file:
  #     - ./hadoop.env

  # datanode:
  #   image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
  #   container_name: datanode
  #   restart: always
  #   volumes:
  #     - hadoop_datanode:/hadoop/dfs/data
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:9870"
  #   env_file:
  #     - ./hadoop.env
  metastore:
    image: metastore
    command: hive --service metastore
    build:
      context: hive-metastore
      dockerfile: Dockerfile
    env_file: 
      - ./hive-metastore/hive.env

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
    volumes: 
      - "./init-hive-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

# volumes:
#   hadoop_namenode:
#   hadoop_datanode:
#   hadoop_historyserver: