version: "3"
services:
  db-init:
    image: hive
    command: schematool -dbType postgres -initSchema --verbose
    build:
      context: hive
      dockerfile: Dockerfile
    env_file:
      - ./hive/hive.env

  hive-server:
    image: hive
    command: hive --service hiveserver2
    build:
      context: hive
      dockerfile: Dockerfile
    env_file:
      - ./hive/hive.env

  hive-metastore:
    image: hive
    # command: >
    #   bash -c "schematool -dbType postgres -initSchema --verbose
    #   && hive --service metastore"
    command: hive --service metastore
    # command: ls /opt/hive/lib
    build:
      context: hive
      dockerfile: Dockerfile
    env_file:
      - ./hive/hive.env
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - "./init-hive-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  presto:
    image: prestosql/presto:332
    ports:
      - 8080:8080
    volumes:
      - "./prestosql/etc:/usr/lib/presto/etc"
# volumes:
#   hadoop_namenode:
#   hadoop_datanode:
#   hadoop_historyserver:
