version: "3"
services:
  db-init:
    image: hive
    command: schematool -dbType postgres -initSchema --verbose
    build:
      context: hive
      dockerfile: Dockerfile
    env_file:
      - ./hive/hive.env

  hive-server:
    image: hive
    command: hiveserver2
    build:
      context: hive
      dockerfile: Dockerfile
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    env_file:
      - ./hive/hive.env

  hive-metastore:
    image: hive
    command: hiveserver2 --service metastore
    environment:
      SERVICE_PRECONDITION: "hive-metastore-postgresql:5432"
    build:
      context: hive
      dockerfile: Dockerfile
    env_file:
      - ./hive/hive.env

  hive-metastore-postgresql:
    container_name: postgres
    image: postgres:12
    volumes:
      - "./init-hive-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data

  presto:
    image: prestosql/presto:332
    ports:
      - 8080:8080
    volumes:
      - "./prestosql/etc:/usr/lib/presto/etc"

  mc:
    image: minio/mc:RELEASE.2020-04-25T00-43-23Z
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      mc config host add super-puper-config http://minio:9000 minio minio123 && \
        mc mb super-puper-config/hive && \
        mc cp myobject.csv super-puper-config/hive/warehouse/users/myobject.csv || exit 1;"
